version: '2'
services:
  laravel-api:
    image: testsmith/practice-software-testing-sprint5-api
    environment:
      - "PHP_OPCACHE_VALIDATE_TIMESTAMPS=1"
      - "DB_PORT=3306"
      - "DB_HOST=mariadb"
      - "host=localhost"
      - DISABLE_LOGGING=true

  angular-ui:
    image: testsmith/practice-software-testing-sprint5-ui
    ports:
      - 4200:4200
    command: >
      bash -c "ng serve --host 0.0.0.0 --port 4200"

  web:
    image: testsmith/practice-software-testing-web
    ports:
      - 8091:80
      - 8000:81
    depends_on:
      - laravel-api

  mariadb:
    image: yobasystems/alpine-mariadb:10.6.11
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: toolshop
