name: Java CI with Maven

on:
  push:
    branches:
      - main
      - issue-*

  pull_request:
    branches:
      - main
      - issue-*

permissions:
    statuses: write
    checks: write
    contents: write
    pull-requests: write

jobs:
  build:
    name: Build and Test  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Start Practice Software Testing ToolShop Website with Docker Compose
      run: docker compose -f docker-compose-toolshop.yml up -d

    - name: Sleep for 90 seconds
      run: sleep 90s
      shell: bash

    - name: Create and Seed Database
      run: docker compose -f docker-compose-toolshop.yml exec laravel-api php artisan migrate:fresh --seed

    - name: GET Version
      run: curl -v -X GET 'http://localhost:8091/status'

    - name: POST login
      run: |
          curl -v -X POST 'http://localhost:8091/users/login' \
          -H 'Content-Type: application/json' \
          --data-raw '{"email":"customer@practicesoftwaretesting.com","password":"welcome01"}'      

    - name: Build Project and run tests
      run: mvn clean install

    - name: Upload screenshots
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-screenshots
        path: screenshots

    - name: Stop Practice Software Testing ToolShop Website
      run: docker compose -f docker-compose-toolshop.yml down --remove-orphans

    - name: Test Report
      uses: dorny/test-reporter@v2
      if: success() || failure()
      with:
        name: Test Results
        path: ${{ github.workspace }}/target/surefire-reports/TEST-TestSuite.xml
        reporter: java-junit
        java-version: 17